// export * from './enfermeriaHomeComponent';
export * from './enfermeriaAsignacionComponent';
export * from './enfermeriaStockPorPisoComponent';
export * from './enfermeriaListadoMovimientosStockComponent';
export * from './productosStockTable';
export * from './enfermeriaAsignacionPorAccionTable';
export * from './enfermeriaVerDetalleMovimiento';
export * from './enfermeriaVerAuditoriaMovimiento';
export * from './enfermeriaGestionEnfermeras';
export * from './enfermeriaNuevoPrestamoEnfermera';
export * from './enfermeriaVerHistorialPrestamoEnfermera';
export * from './enfermeriaUpa';
export * from './enfermeriaIndicacionesMedicas';
export * from './enfermeriaListadoIndicacionesMedicasTab';
export * from './enfermeriaSuministrarEjecucionModalComponent';
export * from './enfermeriaColocarSueroModalComponent';
export * from './enfermeriaSeleccionadorInternadosComponent';