export interface FiltroReporteGenericoDeTurnosDto {
	FechaDesde?: string,
	FechaHasta?: string,
	IdRecurso?: number,
	IdTipoRecurso?: number,
	ListaDeServicios?: Array<number>,
	IdSucursal?: number,
	IdPaciente?: number,
	ListaDeMutuales?: Array<number>,
	IdTipoTurno?: number,
	ListaDeEstadosDeTurnos?:Array<number>,
	IncluirLibres?: boolean,
	IdPrestacion?: number,
	SoloAgendaActiva?: boolean,
	SoloActivos?: boolean,
	IncluirObservaciones?: boolean,
	IncluirMotivoDeCancelacion?: boolean,
	IdEspecialidad?: number,
}
