export interface ITurnoReporteRecepcionConPrefacturaDTO {
	Id?: number,
	Fecha?: string,
	Hora?: string,
	Tipo?: string,
	Documento?: string,
	Paciente?: string,
	MutualTurno?: string,
	ObservacionesTurno?: string,
	TipoTurno?: string,
	IdEstadoTurno?: number,
	EstadoTurno?: string,
	UsuarioAsig?: string,
	FechaAsig?: string,
	HoraAsig?: string,
	UsuarioRecep?: string,
	FechaRecep?: string,
	HoraRecep?: string,
	MutualPrefactura?: string,
	ObservacionesPrefactura?: string,
}
