import * as angular from 'angular'; (function () { 
 angular.module('config', [])

.constant('APP_INFO', {name:'app-sanatorio-allende',title:'App - Sanatorio Allende',description:'Aplicaciones front end del Sanatorio Allende.',main:'src/app/app.js',authors:'Sistemas - Sanatorio Allende',private:true,license:'UNLICENSED',version:'1.0.0',config:{},dependencies:{angular:'~1.5.0','angular-animate':'~1.5.0','angular-bootstrap-contextmenu':'^0.9.9','angular-bootstrap-datetimepicker':'~1.1.4','angular-gridster':'~0.13.14','angular-i18n':'~1.5.0','angular-local-storage':'~0.7.1','angular-messages':'~1.5.0','angular-moment':'~1.1.0','angular-resource':'~1.5.0','angular-sanitize':'~1.5.0','angular-ui-bootstrap':'~2.5.0','angular-ui-grid':'~4.0.7','angular-ui-router':'~0.4.2','angular-ui-switch':'~0.1.1','angularjs-toaster':'~2.2.0',bootstrap:'~3.3.7','font-awesome':'~4.7.0',fullcalendar:'~3.5.1',highcharts:'~6.0.0',moment:'~2.18.0','ng-csv':'~0.3.6','ng-file-upload':'^12.2.13',pdfmake:'~0.1.33'},devDependencies:{'@types/angular':'~1.5.23','@types/angular-animate':'~1.5.8','@types/angular-gridster':'~0.13.5','@types/angular-local-storage':'~0.6.0','@types/angular-resource':'~1.5.14','@types/angular-sanitize':'~1.3.6','@types/angular-ui-bootstrap':'~0.13.46','@types/jquery':'^3.2.15','angular-mocks':'~1.5.0','css-loader':'~0.28.7','extract-text-webpack-plugin':'~3.0.1','file-loader':'~1.1.5',grunt:'~1.0.1','grunt-contrib-clean':'~1.1.0','grunt-karma':'~2.0.0','grunt-ng-constant':'~2.0.1','grunt-sftp-deploy':'~0.2.5','grunt-webpack':'~3.0.2','html-loader':'~0.5.1','html-webpack-plugin':'~2.30.1',jasmine:'~2.8.0','jasmine-core':'~2.8.0',karma:'~1.7.1','karma-chrome-launcher':'~2.2.0','karma-cli':'~1.0.1','karma-firefox-launcher':'~1.0.1','karma-jasmine':'~1.1.0','karma-phantomjs-launcher':'~1.0.4','karma-requirejs':'~1.1.0',matchdep:'~2.0.0','node-sass':'~4.5.3',path:'~0.12.7','phantomjs-prebuilt':'~2.1.15','postcss-loader':'~2.0.6','raw-loader':'~0.5.1',requirejs:'~2.3.5','sass-loader':'~6.0.6','source-map-loader':'^0.2.2','style-loader':'~0.19.0','ts-loader':'~2.3.7',typescript:'~2.5.3','url-loader':'~0.6.2',webpack:'~3.6.0'},peerDependencies:{},scripts:{start:'grunt compile:init && webpack-dev-server','build:dev':'grunt compile:init:dev && webpack -p --config webpack.prod.config.js','build:test':'grunt compile:init:test && webpack -p --config webpack.prod.config.js','build:prod':'grunt compile:init:prod && webpack -p --config webpack.prod.config.js','deploy:dev':'grunt deploy:dev','deploy:test':'grunt deploy:test','deploy:prod':'grunt deploy:prod',test:'node node_modules/karma/bin/karma start config/karma.conf.js','test-single-run':'node node_modules/karma/bin/karma start test/karma.conf.js --single-run'}})

.constant('ENV', {NAME:'local',BACKEND:'http://localhost:8082/api/',TOKEN:'http://localhost:8082/Token',TOKEN_GRANT_TYPE:'password',CLASS:'local'})

.constant('DEBUG', true)

; 

 })();